#!/bin/bash
cd $(dirname $(dirname $0)) || exit

mkdir -p environment problems media nginx

cp ../config_template/wsevent/config.js repo/websocket/
cp ../config_template/site/local_settings.py repo/dmoj/
cp ../config_template/site/uwsgi.ini repo/

cp ../config_template/environment/*.env environment/
cp ../config_template/nginx/nginx.conf nginx/
