version: '3.7'
services:
  db:
    container_name: hnoj_mysql
    image: mariadb
    restart: unless-stopped
    volumes:
      - ./database/:/var/lib/mysql/
    env_file: [environment/mysql.env, environment/mysql-admin.env]
    networks: [db]
  redis:
    container_name: hnoj_redis
    image: redis:alpine
    restart: unless-stopped
    networks: [site]
  base:
    container_name: hnoj_base
    build:
      context: .
      dockerfile: ./base/Dockerfile
    image: hnoj/hnoj-base
    network_mode: none
  site:
    container_name: hnoj_site
    build:
      context: .
      dockerfile: ./site/Dockerfile
    image: hnoj/hnoj-site
    init: true
    restart: unless-stopped
    volumes:
      - assets:/assets/
      - pdfcache:/pdfcache/
      - userdatacache:/userdatacache/
      - contestdatacache:/contestdatacache/
      - cache:/cache/
      - ./media/:/media/
      - ./problems/:/problems/
      - ./repo/:/site/
    working_dir: /site/
    env_file: [environment/mysql.env, environment/site.env]
    networks: [site, nginx, db]
    depends_on: [base, db, redis]
  celery:
    container_name: hnoj_celery
    build:
      context: .
      dockerfile: ./celery/Dockerfile
    image: hnoj/hnoj-celery
    init: true
    restart: unless-stopped
    volumes:
      - userdatacache:/userdatacache/
      - contestdatacache:/contestdatacache/
      - ./repo/:/site/
    working_dir: /site/
    env_file: [environment/mysql.env, environment/site.env]
    networks: [site, db]
    depends_on: [base, db, redis]
  bridged:
    container_name: hnoj_bridged
    build:
      context: .
      dockerfile: ./bridged/Dockerfile
    image: hnoj/hnoj-bridged
    init: true
    restart: unless-stopped
    volumes:
      - ./problems/:/problems/
      - ./repo/:/site/
    working_dir: /site/
    env_file: [environment/mysql.env, environment/site.env]
    networks: [site, nginx, db]
    ports:
      - 9999:9999
    depends_on: [base, db, redis]
  wsevent:
    container_name: hnoj_wsevent
    build:
      context: .
      dockerfile: ./wsevent/Dockerfile
    image: hnoj/hnoj-wsevent
    init: true
    restart: unless-stopped
    volumes:
      - ./repo/:/app/site/
    working_dir: /app/site
    env_file: [environment/mysql.env, environment/site.env]
    networks: [site, nginx]
  nginx:
    container_name: hnoj_nginx
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - assets:/assets/
      - pdfcache:/pdfcache/
      - userdatacache:/userdatacache/
      - contestdatacache:/contestdatacache/
      - cache:/cache/
      - ./media/:/media/
      - ./nginx/:/etc/nginx/conf.d/
    networks: [nginx]
    depends_on: [site, wsevent]
networks:
  site:
  db:
  nginx:
volumes:
  assets:
  pdfcache:
  userdatacache:
  contestdatacache:
  cache:
